# Generated by Django 5.2.6 on 2025-12-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DashboardMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("total_stock", "Total Stock"),
                            ("low_stock_alert", "Low Stock Alert"),
                            ("fast_moving", "Fast Moving Items"),
                            ("overstock", "Overstock"),
                            ("price_change", "Price Change"),
                            ("daily_sales", "Daily Sales"),
                            ("monthly_sales", "Monthly Sales"),
                        ],
                        max_length=50,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "threshold",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Dashboard Metrics",
                "ordering": ["-recorded_at"],
            },
        ),
    ]
