# Generated by Django 5.2.6 on 2025-12-08 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_dashboard", "0001_initial"),
        ("app_inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboardmetric",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app_inventory.lumberproduct",
            ),
        ),
        migrations.AddIndex(
            model_name="dashboardmetric",
            index=models.Index(
                fields=["metric_type", "-recorded_at"],
                name="app_dashboa_metric__ea8aaf_idx",
            ),
        ),
    ]
