# Generated by Django 5.2.6 on 2025-12-08 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_delivery", "0001_initial"),
        ("app_sales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="sales_order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="delivery",
                to="app_sales.salesorder",
            ),
        ),
        migrations.AddField(
            model_name="deliverylog",
            name="delivery",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery_logs",
                to="app_delivery.delivery",
            ),
        ),
    ]
