# Generated by Django 6.0.1 on 2026-01-21 12:48

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_round_wood', '0004_remove_roundwoodpurchaseorderitem_purchase_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundwoodpurchase',
            name='board_feet',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total board feet (L × W × T / 12)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='roundwoodpurchase',
            name='length_inches',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Length in inches for board feet calculation', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='roundwoodpurchase',
            name='thickness_inches',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Thickness in inches for board feet calculation', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='roundwoodpurchase',
            name='unit_cost_per_board_feet',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost per board foot', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='roundwoodpurchase',
            name='width_inches',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Width in inches for board feet calculation', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='roundwoodpurchase',
            name='volume_cubic_feet',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total volume in cubic feet', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
