# Generated by Django 6.0.1 on 2026-01-21 12:57

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_round_wood', '0005_roundwoodpurchase_board_feet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roundwoodpurchase',
            name='unit_cost_per_cubic_foot',
        ),
        migrations.AlterField(
            model_name='roundwoodpurchase',
            name='unit_cost_per_board_feet',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Cost per board foot', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
