# Generated by Django 6.0.1 on 2026-01-21 13:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_round_wood', '0006_remove_cubic_foot_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roundwoodpurchase',
            name='diameter_inches',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Average log diameter in inches', max_digits=5),
        ),
        migrations.AlterField(
            model_name='roundwoodpurchase',
            name='length_feet',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Average log length in feet', max_digits=5),
        ),
    ]
