# Generated by Django 5.2.6 on 2025-12-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_sales", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesorder",
            name="so_number",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
