# Generated by Django 5.2.6 on 2026-01-14 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_sales", "0010_remove_duplicate_customers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorder",
            name="confirmed_at",
            field=models.DateTimeField(
                blank=True, help_text="When the order was confirmed", null=True
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="confirmed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin who confirmed this order",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="confirmed_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="is_confirmed",
            field=models.BooleanField(
                default=False,
                help_text="Order confirmed by admin - prevents further edits",
            ),
        ),
    ]
