# Generated by Django 5.2.6 on 2026-01-14 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_sales", "0011_add_order_confirmation_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipt",
            name="sales_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receipts",
                to="app_sales.salesorder",
            ),
        ),
    ]
