# Generated by Django 5.2.6 on 2026-01-14 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_sales", "0012_change_receipt_to_foreign_key"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="is_pwd",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="is_senior",
        ),
    ]
