# Generated by Django 5.2.6 on 2026-01-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_sales", "0013_remove_senior_pwd_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
