# Generated by Django 5.2.6 on 2025-12-08 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="stocktransaction",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_transactions",
                to="app_inventory.lumberproduct",
            ),
        ),
        migrations.AddIndex(
            model_name="lumberproduct",
            index=models.Index(fields=["sku"], name="app_invento_sku_ca815f_idx"),
        ),
        migrations.AddIndex(
            model_name="lumberproduct",
            index=models.Index(
                fields=["category"], name="app_invento_categor_f7a2ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stocktransaction",
            index=models.Index(
                fields=["product", "-created_at"], name="app_invento_product_b901d1_idx"
            ),
        ),
    ]
