# Generated by Django 5.2.6 on 2025-12-08 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_inventory", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventorySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_pieces", models.IntegerField()),
                (
                    "total_board_feet",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("snapshot_date", models.DateField(auto_now_add=True, db_index=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_snapshots",
                        to="app_inventory.lumberproduct",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Inventory Snapshots",
                "ordering": ["-snapshot_date"],
                "indexes": [
                    models.Index(
                        fields=["product", "-snapshot_date"],
                        name="app_invento_product_597917_idx",
                    )
                ],
                "unique_together": {("product", "snapshot_date")},
            },
        ),
    ]
