# Generated by Django 5.2.6 on 2025-12-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_inventory", "0003_inventorysnapshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lumbercategory",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
